[package]
name = "ckb-sentry"
version = "0.21.0"
authors = ["Sentry <hello@sentry.io>", "Nervos Core Dev <dev@nervos.org>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/nervosnetwork/sentry-rust"
description = """
Sentry (getsentry.com) client for rust ;)
"""
edition = "2018"
autoexamples = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["backtrace", "contexts", "panic", "transport"]

# default integrations
backtrace = ["sentry-backtrace"]
contexts = ["sentry-contexts"]
panic = ["sentry-panic"]
# other integrations
anyhow = ["sentry-anyhow"]
debug-images = ["sentry-debug-images"]
error-chain = ["sentry-error-chain"]
failure = ["sentry-failure"]
log = ["sentry-log"]
slog = ["sentry-slog"]
# other features
test = ["sentry-core/test"]
debug-logs = ["log_", "sentry-core/debug-logs"]
# transports
transport = ["reqwest", "native-tls"]
reqwest = ["reqwest_", "httpdate"]
curl = ["curl_", "httpdate", "serde_json"]
surf = ["surf_", "httpdate", "futures"]
native-tls = ["reqwest_/default-tls"]
rustls = ["reqwest_/rustls-tls"]

[dependencies]
sentry-core = { package = "ckb-sentry-core", version = "0.21.0", path = "../sentry-core", features = ["client"] }
sentry-anyhow = { package = "ckb-sentry-anyhow", version = "0.21.0", path = "../sentry-anyhow", optional = true }
sentry-backtrace = { package = "ckb-sentry-backtrace", version = "0.21.0", path = "../sentry-backtrace", optional = true }
sentry-contexts = { package = "ckb-sentry-contexts", version = "0.21.0", path = "../sentry-contexts", optional = true }
sentry-debug-images = { package = "ckb-sentry-debug-images", version = "0.21.0", path = "../sentry-debug-images", optional = true }
sentry-error-chain = { package = "ckb-sentry-error-chain", version = "0.21.0", path = "../sentry-error-chain", optional = true }
sentry-failure = { package = "ckb-sentry-failure", version = "0.21.0", path = "../sentry-failure", optional = true }
sentry-log = { package = "ckb-sentry-log", version = "0.21.0", path = "../sentry-log", optional = true }
sentry-panic = { package = "ckb-sentry-panic", version = "0.21.0", path = "../sentry-panic", optional = true }
sentry-slog = { package = "ckb-sentry-slog", version = "0.21.0", path = "../sentry-slog", optional = true }
log_ = { package = "log", version = "0.4.8", optional = true, features = ["std"] }
reqwest_ = { package = "reqwest", version = "0.10.8", optional = true, features = ["blocking", "json"], default-features = false }
curl_ = { package = "curl", version = "0.4.25", optional = true }
surf_ = { package = "surf", version = "2.0.0", optional = true }
futures = { version = "0.3", optional = true }
httpdate = { version = "0.3.2", optional = true }
serde_json = { version = "1.0.48", optional = true }

[dev-dependencies]
sentry-anyhow = { package = "ckb-sentry-anyhow", version = "0.21.0", path = "../sentry-anyhow" }
sentry-error-chain = { package = "ckb-sentry-error-chain", version = "0.21.0", path = "../sentry-error-chain" }
sentry-failure = { package = "ckb-sentry-failure", version = "0.21.0", path = "../sentry-failure" }
sentry-log = { package = "ckb-sentry-log", version = "0.21.0", path = "../sentry-log" }
sentry-slog = { package = "ckb-sentry-slog", version = "0.21.0", path = "../sentry-slog" }
log_ = { package = "log", version = "0.4.8", features = ["std"] }
slog_ = { package = "slog", version = "2.5.2" }
failure_derive = "0.1.6"
actix-web = { version = "3", default-features = false }
tokio = { version = "0.2", features = ["macros"] }
failure_ = { package = "failure", version = "0.1.6" }
pretty_env_logger = "0.4.0"
error-chain_ = { package = "error-chain", version = "0.12.1" }
anyhow_ = { package = "anyhow", version = "1.0.30" }
